using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rubenhak.NetflowExporter
{
    public enum FieldType : ushort
    {
        UNKNOWN = 0,
        InputBytes = 1,
        InputPackets = 2,
        Flows = 3,
        Protocol = 4,
        SourceTypeOfService = 5,
        TcpFlags = 6,
        L4SourcePort = 7,
        IPV4SourceAddress = 8,
        SourceMask = 9,
        InputSNMP = 10,
        L4DestionationPort = 11,
        IPV4DestionationAddress = 12,
        DestionationMask = 13,
        OoutputSNMP = 14,
        IPV4NextHop = 15,
        SourceAS = 16,
        DestionationAS = 17,
        BgpIPV4NextHop = 18,
        MulticastDestionationPackets = 19,
        MulticastDestionationBytes = 20,
        LastSwitched = 21,
        FirstSwitched = 22,
        OutputBytes = 23,
        OutputPackets = 24,
        MinPacketLength = 25,
        MaxPacketLength = 26,
        IPV6SourceAddress = 27,
        IPV6DestionationAddress = 28,
        IPV6SourceMask = 29,
        IPV6DestionationMask = 30,
        IPV6FlowLabel = 31,
        IcmpType = 32,
        MulticastIgmpType = 33,
        SamplingInterval = 34,
        SamplingAlgorithm = 35,
        FlowActiveTimeout = 36,
        FlowInactiveTimeout = 37,
        EngineType = 38,
        EngineId = 39,
        TotalBytesExported = 40,
        TotalPacketsExported = 41,
        TotalFlowsExported = 42,
        IPV4SourcePrefix = 44,
        IPV4DestionationPrefix = 45,
        MplsTopLabelType = 46,
        MplsTopLabelIpAddress = 47,
        FlowSamplerId = 48,
        FlowSamplerMode = 49,
        FlowSamplerRandomInterval = 50,
        MinTtl = 52,
        MaxTtl = 53,
        IPV4Ident = 54,
        DestionatioTypeOfService = 55,
        InputSourceMAC = 56,
        OutputDestionation_MAC = 57,
        SourceVLAN = 58,
        DestionationVLAN = 59,
        IpProtocolVersion = 60,
        Direction = 61,
        IPV6NextHop = 62,
        BpgIPV6NextHop = 63,
        IPV6OptionHeaders = 64,
        MplsLabel1 = 70,
        MplsLabel2 = 71,
        MplsLabel3 = 72,
        MplsLabel4 = 73,
        MplsLabel5 = 74,
        MplsLabel6 = 75,
        MplsLabel7 = 76,
        MplsLabel8 = 77,
        MplsLabel9 = 78,
        MplsLabel10 = 79,
        InputDestionationMac = 80,
        OutputSourceMac = 81,
        InterfaceName = 82,
        InterfaceDescription = 83,
        SamplerName = 84,
        InputPermanentBytes = 85,
        InputPermanentPackets = 86,
        FragmentOffset = 88,
        ForwardingStatus = 89,
        MplsPalRouteDistinguisher = 90,
        MplsPrefixLength = 91,
        SourceTrafficIndex = 92,
        DestionationTrafficIndex = 93,
        ApplicationDescription = 94,
        ApplicationTag = 95,
        ApplicationName = 96,
        PostIpDiffServCodePoint = 98,
        ReplicationFactor = 99,
        L2PacketSectionOffset = 102,
        L2PacketSectionSize = 103,
        L2packetSectionData = 104
    }


}
